function Y = removeBelowLocalMaxima(X)

% This function checks whether the centre pixel is greater than equal to
% the maxima or not and then sets the output pixel to zero if it is less 
% than the local maxima or sets it to the value of the centre pixel if the
% condition is satisfied.

% INPUTS:
% X: matrix of size(numPixelsInNeighbourHood, numNeighbourhoods). This
% matrix is generated by the colfilt function.

% RETURNS:
% Y: row vector of size(1, number of columns in X). It contains either 0 or
% the value of the centre pixel depending on the condition.

    [r, c] = size(X);
    Y = zeros(1, c);
    mid = floor(r/2);
    
    for column=1:1:c
        maxx = max(X(:, column));
        if X(mid, column) >= maxx
            Y(1, column) = X(mid, column);
        end;
    end;

end